### ISSUE TITLE
[Pf2E] Unsupported roll on custom Toggle Property RE

### ISSUE THREAD

**Issue by roxim5** [Drental/fvtt-tokenactionhud#140]
Created a custom Toggle Property to apply Volley penalty. TAH doesn't like it and throws an error in console.

`Uncaught (in promise) Error: bow-weapon-group-attack is not a supported roll        main.bundle.js:1 
[Detected 2 packages: system:pf2e, token-action-hud]
    at CharacterPF2e.toggleRollOption (systems/pf2e/main.bundle.js:1:114997)
    at RollHandlerBasePf2e._performToggleMacro (bundle.min.js:1:157562)
    at RollHandlerBasePf2e._handleMacros (bundle.min.js:1:151292)
    at RollHandlerBasePf2e.doHandleActionEvent (bundle.min.js:1:150650)
    at RollHandlerBasePf2e.handleActionEvent (bundle.min.js:1:33213)
    at handleClick (bundle.min.js:1:10135)
    at HTMLDivElement.<anonymous> (bundle.min.js:1:10782)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at HTMLDivElement.v.handle (jquery.min.js:2:41048)`
![image](https://user-images.githubusercontent.com/89946334/148897131-bc4bb544-dcff-4d6c-9a2c-e71f2fb6e13b.png)
[fvtt-Actor-drosil.zip](https://github.com/Drental/fvtt-tokenactionhud/files/7844416/fvtt-Actor-drosil.zip)

**Comment by Drental** [comment]
is this still an issue?

**Comment by roxim5** [comment]
Unsure but I haven't ran into it since. You can close this.
