### ISSUE TITLE
PF2e attack buttons - right click throws error

### ISSUE THREAD

**Issue by itamarcu** [Drental/fvtt-tokenactionhud#163]
When right-clicking any of the following buttons:

![image](https://user-images.githubusercontent.com/6516621/154821936-f1bec8df-40b7-4565-bd98-693df5cfe482.png)

An error is thrown:

```js
bundle.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sheet')
[Detected 1 package: token-action-hud]
    at RollHandlerBasePf2e.doRenderItem (bundle.min.js:1:33579)
    at RollHandlerBasePf2e._rollStrikeChar (bundle.min.js:1:153730)
    at RollHandlerBasePf2e._handleMacros (bundle.min.js:1:151437)
    at RollHandlerBasePf2e.doHandleActionEvent (bundle.min.js:1:150744)
    at RollHandlerBasePf2e.handleActionEvent (bundle.min.js:1:33222)
    at handleClick (bundle.min.js:1:10135)
    at HTMLDivElement.<anonymous> (bundle.min.js:1:10836)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at HTMLDivElement.v.handle (jquery.min.js:2:41048)
```

I didn't expect right-clicking to do anything, but it's better to ignore than to log an error.

**Comment by Drental** [comment]
feeeexed
