### ISSUE TITLE
Error message when selecting more more than one token

### ISSUE THREAD

**Issue by bemdesign-er** [Drental/fvtt-tokenactionhud#259]
Setup: Foundry v10, DnD5e system (2.0.2), Token Action HUD (3.0.2)

Seeing this error message when selecting more than one token.
```Uncaught (in promise) TypeError: i.charAt is not a function
[Detected 1 package: token-action-hud]
    at bundle.min.js:1:53422
    at Array.map (<anonymous>)
    at ActionHandler5e._addMultiSkills (bundle.min.js:1:53391)
    at ActionHandler5e._buildMultipleTokenList (bundle.min.js:1:46479)
    at ActionHandler5e.doBuildActionList (bundle.min.js:1:45161)
    at ActionHandler5e.buildActionList (bundle.min.js:1:30728)
    at TokenActionHUD.updateHud (bundle.min.js:1:16716)```

**Comment by Larkinabout** [comment]
I'll take a look tomorrow if no one jumps on it before then.
