### ISSUE TITLE
PF2e 4.1.0 appears to break strikes/weapons in Token Action HUD

### ISSUE THREAD

**Issue by DaringMarble** [Drental/fvtt-tokenactionhud#277]
When using Token Action HUD with the latest PF2e version, strikes produce the following error: 

    Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'variants')
[Detected 1 package: token-action-hud]
    at RollHandlerBasePf2e._rollStrikeChar (bundle.min.js:1:159578)
    at RollHandlerBasePf2e._handleMacros (bundle.min.js:1:157307)
    at RollHandlerBasePf2e.doHandleActionEvent (bundle.min.js:1:156619)
    at RollHandlerBasePf2e.handleActionEvent (bundle.min.js:1:35791)
    at handleClick (bundle.min.js:1:13102)
    at HTMLDivElement.<anonymous> (bundle.min.js:1:13761)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

This error appears to only impact strikes and weapons (though I did limited testing).

**Comment by Drental** [comment]
strike.name got renamed to strike.label
gonna try and fix this.
