### ISSUE TITLE
Bug when selecting multiple tokens that aren't linked to any actor (PF2e?)

### ISSUE THREAD

**Issue by shemetz** [Drental/fvtt-tokenactionhud#313]
> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')
[Detected 1 package: token-action-hud]
    at bundle.min.js:1:142692
    at Array.filter (<anonymous>)
    at ActionHandlerPf2e._buildMultipleTokenList (bundle.min.js:1:142668)
    at ActionHandlerPf2e.doBuildActionList (bundle.min.js:1:142152)
    at ActionHandlerPf2e.buildActionList (bundle.min.js:1:39862)
    at TokenActionHUD.updateHud (bundle.min.js:1:25578)

Reproduce by:

1. create a token
2. set it to represent None
3. copy and paste it
4. select both copies

**Comment by Larkinabout** [comment]
Fixed in release 3.0.13.
