### ISSUE TITLE
(Star Wars FFG) [BUG] Most Skill Rolls broken

### ISSUE THREAD

**Issue by LukeSolas** [Drental/fvtt-tokenactionhud#363]
Most Skills  throw the following error when the roll builder is opened via the Token Action Hud buttons wiht the Star Wars FFG System.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'hasOwnProperty')             roll-builder.js:138 
    at HTMLButtonElement.<anonymous> (roll-builder.js:138:94)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

reproduced it with only this module and its dependencies activated.

**Comment by Larkinabout** [comment]
StarWarsFoundryVTT/StarWarsFFG#1146

**Comment by Larkinabout** [comment]
Resolved on the system side.
