### ISSUE TITLE
[PF2e] Using a newly created weapons throws an error

### ISSUE THREAD

**Issue by oWave** [Drental/fvtt-tokenactionhud#368]
Interacting (drawing or rolling a strike) with a newly created weapon on a PC sheet throws the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'variants')
    at RollHandlerBasePf2e._rollStrikeChar (bundle.min.js:formatted:6719:19)
    at RollHandlerBasePf2e._handleMacros (bundle.min.js:formatted:6578:22)
    at RollHandlerBasePf2e.doHandleActionEvent (bundle.min.js:formatted:6539:32)
    at RollHandlerBasePf2e.handleActionEvent (bundle.min.js:formatted:1919:94)
    at handleClick (bundle.min.js:formatted:874:38)
    at HTMLDivElement.<anonymous> (bundle.min.js:formatted:919:17)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

## Replication
- Create a new PC actor
- In the inventory tab, add a new weapon with the plus icon
- Try to draw the weapon with Token HUD in the Strikes menu

Issue does not happen on version 3.0.17

**Comment by Larkinabout** [comment]
Fixed in release 3.0.19.
