### ISSUE TITLE
[SFRPG] Console error in ActionHandleSfrpg._addSpellInfo

### ISSUE THREAD

**Issue by ElroTheOnk** [Drental/fvtt-tokenactionhud#369]
Looks like a v9 -> v10 update problem: console error message below.

Error: You are accessing the ItemSFRPG#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at ItemSFRPG._logV10CompatibilityWarning (commons.js:6642:14)
    at get data [as data] (commons.js:6542:24)
    at ActionHandlerSfrpg._addSpellInfo (bundle.min.js:1:174456)
    at bundle.min.js:1:174359
    at Array.map (<anonymous>)
    at ActionHandlerSfrpg._addSubcategoryByLevel (bundle.min.js:1:174281)
    at ActionHandlerSfrpg._buildSpellsCategory (bundle.min.js:1:171503)
    at ActionHandlerSfrpg.doBuildActionList (bundle.min.js:1:169543)
    at ActionHandlerSfrpg.buildActionList (bundle.min.js:1:41367)
    at TokenActionHUD.updateHud (bundle.min.js:1:27083)

**Comment by Larkinabout** [comment]
Fixed in release 3.0.19.
