### ISSUE TITLE
[Error] - System: D&D 5e - Type error on token select

### ISSUE THREAD

**Issue by timtombam104** [Drental/fvtt-tokenactionhud#411]
**Description**
When clicking on a token to load the action HUD in DnD:5e 2.2 nothing loads and throws the below error

bundle.min.js:1 Uncaught (in promise) TypeError: n.charAt is not a function
    at bundle.min.js:1:61357
    at Array.map (<anonymous>)
    at ActionHandler5e._getAbilityList (bundle.min.js:1:61298)
    at ActionHandler5e._buildAbilitiesCategory (bundle.min.js:1:52037)
    at ActionHandler5e._buildCategories (bundle.min.js:1:51547)
    at ActionHandler5e._buildSingleTokenList (bundle.min.js:1:51242)
    at ActionHandler5e.doBuildActionList (bundle.min.js:1:50946)
    at ActionHandler5e.buildActionList (bundle.min.js:1:41363)
    at TokenActionHUD.updateHud (bundle.min.js:1:27079)
    
**Versions**
Module: 3.0.21
Foundry: 10.219
dnd5e: 2.2.1

**No other modules loaded.**

**Comment by Larkinabout** [comment]
Hi @timtombam104, support for D&D 5e has now moved to the dedicated [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e) module.
