### ISSUE TITLE
[classic] _getAbilityList incompatible with dnd5e 2.2.0

### ISSUE THREAD

**Issue by Thorarin** [Drental/fvtt-tokenactionhud#413]
Amongst the breaking changes for the dnd5e 2.2.0 system, there is mention of the following:

> Abilities
The structure of DND5E.abilities has changed, which each ability value an object now instead of a translation string. The object includes the abbreviation translation string, making DND5E.abilityAbbreviations redundant.

This change causes an error in https://github.com/Drental/fvtt-tokenactionhud/blob/e622d70f7f3b103bbb122df6af5891007d01e9f6/scripts/actions/dnd5e/dnd5e-actions.js#LL657C59-L657C59, because `name` is now an object, not a string.

```
bundle.min.js:1 Uncaught (in promise) TypeError: n.charAt is not a function
    at bundle.min.js:1:61357
    at Array.map (<anonymous>)
    at ActionHandler5e._getAbilityList (bundle.min.js:1:61298)
    at ActionHandler5e._buildAbilitiesCategory (bundle.min.js:1:52037)
    at ActionHandler5e._buildCategories (bundle.min.js:1:51547)
    at ActionHandler5e._buildSingleTokenList (bundle.min.js:1:51242)
    at ActionHandler5e.doBuildActionList (bundle.min.js:1:50946)
    at ActionHandler5e.buildActionList (bundle.min.js:1:41363)
    at TokenActionHUD.updateHud (bundle.min.js:1:27079)
```

I'd make a pull request, but I don't fully understand the surrounding code. The preceding line `let name = abbr ? e[0] : e[1];` is probably dealing with some backward compatibility with even earlier versions of the dnd5e system?

**Comment by Larkinabout** [comment]
Hi @Thorarin, support for D&D 5e has now moved to the dedicated [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e) module.
