### ISSUE TITLE
V10/V11: TypeError: undefined. n.charAt is not a function

### ISSUE THREAD

**Issue by Xirema** [Drental/fvtt-tokenactionhud#419]
I originally saw this error in Foundry V10, but the error is occurring in V11 as well. Error started occurring after I updated the DnD53 version, so I believe it's related to that, not to the Foundry Version.

Foundry Version: Version 11 Stable, Build 301
DnD5e Version: 2.2.1

```
Uncaught (in promise) TypeError: undefined. n.charAt is not a function
[Detected 1 package: token-action-hud]
    at bundle.min.js:1:61357
    at Array.map (<anonymous>)
    at ActionHandler5e._getAbilityList (bundle.min.js:1:61298)
    at ActionHandler5e._buildAbilitiesCategory (bundle.min.js:1:52037)
    at ActionHandler5e._buildCategories (bundle.min.js:1:51547)
    at ActionHandler5e._buildSingleTokenList (bundle.min.js:1:51242)
    at ActionHandler5e.doBuildActionList (bundle.min.js:1:50946)
    at ActionHandler5e.buildActionList (bundle.min.js:1:41363)
    at TokenActionHUD.updateHud (bundle.min.js:1:27079)
(anonymous) @ bundle.min.js:1
_getAbilityList @ bundle.min.js:1
_buildAbilitiesCategory @ bundle.min.js:1
_buildCategories @ bundle.min.js:1
_buildSingleTokenList @ bundle.min.js:1
doBuildActionList @ bundle.min.js:1
buildActionList @ bundle.min.js:1
updateHud @ bundle.min.js:1
setTimeout (async)
update @ bundle.min.js:1
(anonymous) @ bundle.min.js:1
#call @ foundry.js:730
callAll @ foundry.js:687
control @ foundry.js:28203
_onClickLeft @ foundry.js:28592
_onClickLeft @ foundry.js:55650
callback @ foundry.js:31280
#handleClickLeft @ foundry.js:31467
#handleMouseDown @ foundry.js:31452
notifyListeners @ earcut.js:128
notifyTarget @ earcut.js:128
propagate @ earcut.js:128
dispatchEvent @ earcut.js:128
mapPointerDown @ earcut.js:128
mapEvent @ earcut.js:128
onPointerDown @ earcut.js:128
```

**Comment by Larkinabout** [comment]
Hi @Xirema, support for D&D 5e has now moved to the dedicated [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e) module.
